import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import $RefParser from '@apidevtools/json-schema-ref-parser/dist/lib/index.js';
import { compile } from 'json-schema-to-typescript';

import {
  assertGeneratedQuality,
  createAuthoredQuality,
  createCompiledQuality,
  postprocessAuthored,
  postprocessCompiled,
} from './codegen/postprocess.js';
import {
  assertFragmentsAlignedWithSchema,
  buildFragmentsFromSchema,
  loadDomainIdSets,
} from './codegen/schema-metadata.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const schemaDir = path.join(repoRoot, 'schema');
const typesDir = path.join(repoRoot, 'app/src/lib/types');

const AUTHORED_BANNER =
  '/* eslint-disable @typescript-eslint/no-explicit-any -- MilestoneRow §12.8 photo-key tolerance */\n' +
  '/**\n' +
  ' * GENERATED by tools/src/gen-types.ts — do not edit.\n' +
  ' */\n\n';

const COMPILED_BANNER =
  '/**\n' +
  ' * GENERATED by tools/src/gen-types.ts — do not edit.\n' +
  ' */\n\n';

const AUTHORED_SCHEMAS = [
  { file: 'tree.schema.json', exportName: 'Tree' },
  { file: 'domains.schema.json', exportName: 'DomainsFile' },
  { file: 'facets.schema.json', exportName: 'FacetsFile' },
  { file: 'map.schema.json', exportName: 'MapFile' },
  { file: 'export.schema.json', exportName: 'ExportFileDocument' },
] as const;

const COMPILED_SCHEMAS = [
  { file: 'compiled-tree.schema.json', exportName: 'CompiledTree' },
  { file: 'manifest.schema.json', exportName: 'Manifest' },
] as const;

async function generateFromSchema(relativePath: string, exportName: string): Promise<string> {
  const schemaPath = path.join(schemaDir, relativePath);
  const bundled = await $RefParser.bundle(schemaPath);
  const ts = await compile(bundled as Parameters<typeof compile>[0], exportName, {
    bannerComment: '',
    additionalProperties: false,
    enableConstEnums: false,
    strictIndexSignatures: true,
    unknownAny: false,
    unreachableDefinitions: true,
  });

  return ts;
}

async function generateBundle(
  schemas: ReadonlyArray<{ file: string; exportName: string }>,
  banner: string,
): Promise<string> {
  const chunks: string[] = [];
  for (const { file, exportName } of schemas) {
    chunks.push(await generateFromSchema(file, exportName));
  }
  return banner + chunks.join('\n');
}

export async function generateTypes(): Promise<void> {
  mkdirSync(typesDir, { recursive: true });

  const authoredRaw = await generateBundle(AUTHORED_SCHEMAS, AUTHORED_BANNER);
  const compiledRaw = await generateBundle(COMPILED_SCHEMAS, COMPILED_BANNER);

  const fragments = buildFragmentsFromSchema();
  assertFragmentsAlignedWithSchema(fragments);

  const domainIds = loadDomainIdSets();
  const authored = postprocessAuthored(authoredRaw, fragments);
  const compiled = postprocessCompiled(compiledRaw, fragments);

  assertGeneratedQuality(authored, 'authored.d.ts', createAuthoredQuality(domainIds.all));
  assertGeneratedQuality(compiled, 'compiled.d.ts', createCompiledQuality(domainIds.all));

  writeFileSync(path.join(typesDir, 'authored.d.ts'), authored, 'utf8');
  writeFileSync(path.join(typesDir, 'compiled.d.ts'), compiled, 'utf8');
}

const isDirectRun = process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirectRun) {
  await generateTypes();
}
