import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { loadValidationContext } from '../validate/context.js';
import { contentDir, defaultRepoRoot } from '../shared/paths.js';
import { EXIT_OK, EXIT_RUNTIME_ERROR, EXIT_VALIDATION_FAILED } from '../shared/exit-codes.js';
import type { LoadedTree, Provenance } from '../validate/types.js';

const EMPTY_CELL = '—';

function resolveRepoRoot(repoRoot?: string): string {
  return repoRoot ?? process.env.LST_REPO_ROOT ?? defaultRepoRoot;
}

export function reviewStatusPath(repoRoot: string): string {
  return path.join(contentDir(repoRoot), 'REVIEW-STATUS.md');
}

/** A pipe in a name would end the cell early and silently reshape the table. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function authorsCell(provenance: Provenance): string {
  const authors = provenance.authors ?? [];
  if (authors.length === 0) {
    return EMPTY_CELL;
  }
  return authors
    .map((author) => (author.role === 'reviser' ? `${author.name} (reviser)` : author.name))
    .join(', ');
}

function reviewCell(provenance: Provenance, round: number): string {
  const review = (provenance.reviews ?? []).find((entry) => entry.round === round);
  return review ? `${review.reviewer} (${review.date})` : EMPTY_CELL;
}

/**
 * §6.6: generated, never hand-maintained. The header says so in the file itself
 * because the only thing standing between a contributor and a wasted edit is
 * whether they read this line before the table.
 */
export function renderReviewStatus(trees: readonly LoadedTree[]): string {
  const rows = [...trees]
    .sort((a, b) => a.tree.id.localeCompare(b.tree.id))
    .map((loaded) => {
      const provenance = loaded.tree.provenance;
      return `| ${cell(loaded.tree.id)} | ${cell(authorsCell(provenance))} | ${cell(
        reviewCell(provenance, 1),
      )} | ${cell(reviewCell(provenance, 2))} |`;
    });

  return [
    '# Review status',
    '',
    '<!-- Generated by `lst status` from each tree\'s `provenance` block (ARCHITECTURE §6.6).',
    '     Do not edit by hand — CI regenerates this file and fails the merge on any drift. -->',
    '',
    '| Tree | Authored | Review 1 | Review 2 |',
    '|---|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}

export interface StatusOptions {
  repoRoot?: string;
}

export interface StatusResult {
  path: string;
  content: string;
  trees: LoadedTree[];
  /** True when the committed file did not already match what was generated. */
  drifted: boolean;
}

export function runStatus(options: StatusOptions = {}): StatusResult {
  const repoRoot = resolveRepoRoot(options.repoRoot);
  const ctx = loadValidationContext(repoRoot, []);
  const filePath = reviewStatusPath(repoRoot);
  const content = renderReviewStatus(ctx.trees);
  const committed = existsSync(filePath) ? readFileSync(filePath, 'utf8') : null;
  const drifted = committed !== content;

  if (drifted) {
    mkdirSync(path.dirname(filePath), { recursive: true });
    writeFileSync(filePath, content, 'utf8');
  }

  return { path: filePath, content, trees: ctx.trees, drifted };
}

/**
 * **Drift is the only thing that gates.** D-16: a missing review round is a
 * fact about the content, and F42 leaves that judgment to humans; what CI can
 * usefully refuse is a table that no longer describes the trees. So a corpus
 * with no reviews recorded anywhere passes, and a hand-edited table fails.
 *
 * On drift the regenerated file is written before the failure, so the fix is
 * already in the working tree — the same ergonomics as `lst ids` and
 * `lst version` (§6.2, §6.4 check 5).
 */
export function statusCommand(repoRoot?: string): number {
  try {
    const result = runStatus({ repoRoot: resolveRepoRoot(repoRoot) });
    if (result.drifted) {
      console.error(
        `${result.path} was out of date and has been regenerated; commit the result.`,
      );
      return EXIT_VALIDATION_FAILED;
    }
    return EXIT_OK;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return EXIT_RUNTIME_ERROR;
  }
}
