/* eslint-disable @typescript-eslint/no-explicit-any -- MilestoneRow §12.8 photo-key tolerance */
/**
 * GENERATED by tools/src/gen-types.ts — do not edit.
 */

export interface Tree {
  schemaVersion: 1;
  /**
   * Per-tree version; increments when compiled output changes (§5.3).
   */
  contentVersion: number;
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  title: string;
  summary: string;
  /**
   * Locked domain identifier from domains.yaml (§5.9, F20).
   */
  domain: "mind" | "body" | "making" | "home" | "people" | "work-money" | "play" | "outdoors-nature";
  secondaryDomains?: ("mind" | "body" | "making" | "home" | "people" | "work-money" | "play" | "outdoors-nature")[];
  subregion?: "expression" | "objects" | "systems";
  facets?: string[];
  archetype?: "single-track" | "dual-track" | "modular";
  /**
   * @minItems 1
   */
  tracks?: [Track, ...Track[]];
  provenance: Provenance;
  levels: Levels;
  mastery?: MasteryEntry[];
  lineage?: LineageEntry[];
}
/**
 * @minItems 10
 * @maxItems 10
 *
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "levels".
 */
export type Levels = [
  AuthoredLevel & { level: 1 },
  AuthoredLevel & { level: 2 },
  AuthoredLevel & { level: 3 },
  AuthoredLevel & { level: 4 },
  AuthoredLevel & { level: 5 },
  AuthoredLevel & { level: 6 },
  AuthoredLevel & { level: 7 },
  AuthoredLevel & { level: 8 },
  AuthoredLevel & { level: 9 },
  AuthoredLevel & { level: 10 }
];
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "requirementGroup".
 */
export type RequirementGroup =
  | {
      rule: 'all';
      milestones: string[];
      n?: never;
    }
  | {
      rule: 'n_of';
      n: number;
      milestones: string[];
    }
  | {
      rule: 'any';
      milestones: string[];
      n?: never;
    };

/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "track".
 */
export interface Track {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  title: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "provenance".
 */
export interface Provenance {
  /**
   * @minItems 1
   */
  authors: [Author, ...Author[]];
  reviews?: Review[];
  sources?: Source[];
  /**
   * F45 checklist answer — required, no default.
   */
  copyleftDerived: boolean;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "author".
 */
export interface Author {
  name: string;
  github?: string;
  role?: "reviser";
  since?: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "review".
 */
export interface Review {
  round: number;
  reviewer: string;
  date: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "source".
 */
export interface Source {
  title: string;
  url?: string;
  adapted?: "structure" | "sequencing" | "none";
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "masteryEntry".
 */
export interface MasteryEntry {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  /**
   * Immutable Crockford base32 identifier; optional at authoring time (§5.4).
   */
  uid?: string;
  title: string;
  detail?: string;
  requires?: string[];
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "lineageEntry".
 */
export interface LineageEntry {
  /**
   * Immutable Crockford base32 identifier; optional at authoring time (§5.4).
   */
  uid: string;
  op: "split" | "merged" | "retired" | "moved";
  into?: string[];
  note?: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "levelBody".
 */
export interface AuthoredLevel {
  level: number;
  /**
   * @minItems 4
   * @maxItems 8
   */
  milestones:
    | [Milestone, Milestone, Milestone, Milestone]
    | [Milestone, Milestone, Milestone, Milestone, Milestone]
    | [Milestone, Milestone, Milestone, Milestone, Milestone, Milestone]
    | [Milestone, Milestone, Milestone, Milestone, Milestone, Milestone, Milestone]
    | [Milestone, Milestone, Milestone, Milestone, Milestone, Milestone, Milestone, Milestone];
  /**
   * @minItems 1
   */
  requirements?: [RequirementGroup, ...RequirementGroup[]];
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "milestone".
 */
export interface Milestone {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  /**
   * Immutable Crockford base32 identifier; optional at authoring time (§5.4).
   */
  uid?: string;
  aliases?: string[];
  title: string;
  /**
   * Short form for the tree node box (§9.2). Optional; the renderer falls back to title. Capped because the node is 100×44 layout units and cannot legibly show more — see docs/SCHEMA-REVIEW-P0.md finding 1.
   */
  label?: string;
  detail?: string;
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  track?: string;
  order?: number;
  module?: string;
  requires?: string[];
}

/**
 * This interface was referenced by `DomainsFile`'s JSON-Schema
 * via the `definition` "domain".
 */
/** Locked content domain ids declared in common.schema.json (§5.9, F20). */
export type ContentDomainId = 'mind' | 'body' | 'making' | 'home' | 'people' | 'work-money' | 'play' | 'outdoors-nature';

export interface MakingDomain {
  id: 'making';
  title: string;
  blurb: string;
  palette: {
    base: string;
    accent: string;
  };
  subregions: [
    {
      id: 'expression' | 'objects' | 'systems';
      title: string;
    },
    ...{
      id: 'expression' | 'objects' | 'systems';
      title: string;
    }[]
  ];
}

export type ContentNonMakingDomainId = 'mind' | 'body' | 'home' | 'people' | 'work-money' | 'play' | 'outdoors-nature';

export interface NonMakingDomain {
  id: ContentNonMakingDomainId;
  title: string;
  blurb: string;
  palette: {
    base: string;
    accent: string;
  };
  subregions?: never;
}

/** Domain taxonomy entry. Runtime schema requires subregions iff id is making (§5.9). */
export type Domain = MakingDomain | NonMakingDomain;

export interface DomainsFile {
  schemaVersion: 1;
  /**
   * @minItems 1
   */
  domains: [Domain, ...Domain[]];
}
/**
 * This interface was referenced by `DomainsFile`'s JSON-Schema
 * via the `definition` "subregion".
 */
export interface Subregion {
  id: "expression" | "objects" | "systems";
  title: string;
}

export interface FacetsFile {
  schemaVersion: 1;
  /**
   * @minItems 1
   */
  facets: [Facet, ...Facet[]];
}
/**
 * This interface was referenced by `FacetsFile`'s JSON-Schema
 * via the `definition` "facet".
 */
export interface Facet {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  title: string;
  note?: string;
}

/**
 * @minItems 2
 * @maxItems 2
 */
export type AxialTile = [number, number];

export interface MapFile {
  schemaVersion: 1;
  hexSize: number;
  /**
   * @minItems 1
   */
  regions: [Region, ...Region[]];
}
/**
 * This interface was referenced by `MapFile`'s JSON-Schema
 * via the `definition` "region".
 */
export interface Region {
  /**
   * Locked domain identifier from domains.yaml (§5.9, F20).
   */
  domain: "mind" | "body" | "making" | "home" | "people" | "work-money" | "play" | "outdoors-nature";
  /**
   * @minItems 1
   */
  tiles: [AxialTile, ...AxialTile[]];
  label?: {
    q: number;
    r: number;
  };
  /**
   * @minItems 1
   */
  subregions?: [SubregionTiles, ...SubregionTiles[]];
}
/**
 * This interface was referenced by `MapFile`'s JSON-Schema
 * via the `definition` "subregionTiles".
 */
export interface SubregionTiles {
  id: "expression" | "objects" | "systems";
  /**
   * @minItems 1
   */
  tiles: [AxialTile, ...AxialTile[]];
}

export interface ExportFileDocument {
  format: "life-xp-skill-tracker/progress";
  schemaVersion: number;
  exportedAt: string;
  appVersion: string;
  generated: string;
  skills: SkillRow[];
  milestones: MilestoneRow[];
  orphans: OrphanRow[];
}
/**
 * This interface was referenced by `ExportFileDocument`'s JSON-Schema
 * via the `definition` "skillRow".
 */
export interface SkillRow {
  treeId: string;
  startedAt: string;
  attainedLevel: number;
  lastActivityAt: string;
  contentVersionSeen: number;
  grandfathered: Record<string, FrozenSatisfaction>;
}
/**
 * This interface was referenced by `ExportFileDocument`'s JSON-Schema
 * via the `definition` "frozenSatisfaction".
 */
export interface FrozenSatisfaction {
  uids: string[];
  contentVersion: number;
}
/**
 * This interface was referenced by `ExportFileDocument`'s JSON-Schema
 * via the `definition` "milestoneRow".
 */
export interface MilestoneRow {
  /**
   * Immutable Crockford base32 identifier; optional at authoring time (§5.4).
   */
  uid: string;
  treeId: string;
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  slug: string;
  title: string;
  state: "complete" | "dismissed";
  at: string;
  note?: string;
  contentVersion: number;
  [k: string]: any | undefined;
}
/**
 * This interface was referenced by `ExportFileDocument`'s JSON-Schema
 * via the `definition` "orphanRow".
 */
export interface OrphanRow {
  /**
   * Immutable Crockford base32 identifier; optional at authoring time (§5.4).
   */
  uid: string;
  treeId: string;
  title: string;
  state: "complete" | "dismissed";
  at: string;
  note?: string;
  reason: "retired" | "merged" | "unknown";
}
