/**
 * GENERATED by tools/src/gen-types.ts — do not edit.
 */

export interface CompiledTree {
  schemaVersion: 1;
  contentVersion: number;
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  title: string;
  summary: string;
  /**
   * Locked domain identifier from domains.yaml (§5.9, F20).
   */
  domain: "mind" | "body" | "making" | "home" | "people" | "work-money" | "play" | "outdoors-nature";
  secondaryDomains?: ("mind" | "body" | "making" | "home" | "people" | "work-money" | "play" | "outdoors-nature")[];
  subregion?: "expression" | "objects" | "systems";
  facets?: string[];
  archetype?: "single-track" | "dual-track" | "modular";
  /**
   * @minItems 1
   */
  tracks?: [Track, ...Track[]];
  provenance: Provenance;
  levels: Levels;
  mastery?: MasteryEntry[];
  lineage?: LineageEntry[];
  /**
   * Flat milestone index used by compiled slug references.
   */
  milestones: CompiledMilestone[];
}
/**
 * @minItems 10
 * @maxItems 10
 *
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "levels".
 */
export type Levels = [
  CompiledLevel & { level: 1 },
  CompiledLevel & { level: 2 },
  CompiledLevel & { level: 3 },
  CompiledLevel & { level: 4 },
  CompiledLevel & { level: 5 },
  CompiledLevel & { level: 6 },
  CompiledLevel & { level: 7 },
  CompiledLevel & { level: 8 },
  CompiledLevel & { level: 9 },
  CompiledLevel & { level: 10 }
];
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "requirementGroup".
 */
export type RequirementGroup =
  | {
      rule: 'all';
      milestones: [MilestoneRef, ...MilestoneRef[]];
      n?: never;
    }
  | {
      rule: 'n_of';
      n: number;
      milestones: [MilestoneRef, ...MilestoneRef[]];
    };

/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "track".
 */
export interface Track {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  title: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "provenance".
 */
export interface Provenance {
  /**
   * @minItems 1
   */
  authors: [Author, ...Author[]];
  reviews?: Review[];
  sources?: Source[];
  copyleftDerived: boolean;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "author".
 */
export interface Author {
  name: string;
  github?: string;
  role?: "reviser";
  since?: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "review".
 */
export interface Review {
  round: number;
  reviewer: string;
  date: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "source".
 */
export interface Source {
  title: string;
  url?: string;
  adapted?: "structure" | "sequencing" | "none";
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "masteryEntry".
 */
export interface MasteryEntry {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  /**
   * Immutable Crockford base32 identifier; required in compiled output (§5.4).
   */
  uid: string;
  title: string;
  detail?: string;
  requires?: MasteryRequiresRef[];
}
/**
 * Compiled prerequisite reference for mastery entries (§5.7: milestones or other achievements).
 *
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "masteryRequiresRef".
 */
/** Compiled prerequisite reference for mastery entries (§5.7). */
export interface MasteryRequiresRef {
  kind: 'milestone' | 'achievement';
  /** Index into CompiledTree.milestones when kind is milestone, or CompiledTree.mastery when kind is achievement. */
  index: number;
  slug: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "lineageEntry".
 */
export interface LineageEntry {
  /**
   * Immutable Crockford base32 identifier; optional at authoring time (§5.4).
   */
  uid: string;
  op: "split" | "merged" | "retired" | "moved";
  into?: string[];
  note?: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "compiledMilestone".
 */
export interface CompiledMilestone {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  /**
   * Immutable Crockford base32 identifier; required in compiled output (§5.4).
   */
  uid: string;
  aliases?: string[];
  title: string;
  /**
   * Short form for the tree node box (§9.2). Optional; the renderer falls back to title. Capped because the node is 100×44 layout units and cannot legibly show more — see docs/SCHEMA-REVIEW-P0.md finding 1.
   */
  label?: string;
  detail?: string;
  level: number;
  track: "" | string;
  trackIndex: number;
  order: number;
  module?: string;
  requires?: MilestoneRef[];
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "milestoneRef".
 */
export interface MilestoneRef {
  index: number;
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  slug: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "levelBody".
 */
export interface CompiledLevel {
  level: number;
  /**
   * @minItems 4
   * @maxItems 8
   */
  milestones:
    | [MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef]
    | [MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef]
    | [MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef]
    | [MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef]
    | [MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef, MilestoneRef];
  /**
   * @minItems 1
   */
  requirements: [RequirementGroup, ...RequirementGroup[]];
}

/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "compiledDomain".
 */
/** Locked content domain ids declared in common.schema.json (§5.9, F20). */
export type ContentDomainId = 'mind' | 'body' | 'making' | 'home' | 'people' | 'work-money' | 'play' | 'outdoors-nature';

export interface CompiledMakingDomain {
  id: 'making';
  title: string;
  blurb: string;
  palette: {
    base: string;
    accent: string;
  };
  subregions: [
    {
      id: 'expression' | 'objects' | 'systems';
      title: string;
    },
    ...{
      id: 'expression' | 'objects' | 'systems';
      title: string;
    }[]
  ];
}

export type ContentNonMakingDomainId = 'mind' | 'body' | 'home' | 'people' | 'work-money' | 'play' | 'outdoors-nature';

export interface CompiledNonMakingDomain {
  id: ContentNonMakingDomainId;
  title: string;
  blurb: string;
  palette: {
    base: string;
    accent: string;
  };
  subregions?: never;
}

/** Compiled domain taxonomy entry. Runtime schema requires subregions iff id is making (§5.9). */
export type CompiledDomain = CompiledMakingDomain | CompiledNonMakingDomain;

export interface Manifest {
  schemaVersion: 1;
  generated: string;
  taxonomy: Taxonomy;
  trees: TreeEntry[];
  /**
   * uid → destination tree id for every op:moved entry (§7.2).
   */
  moved: Record<string, string>;
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "taxonomy".
 */
export interface Taxonomy {
  domains: CompiledDomain[];
  facets: CompiledFacet[];
  map: {
    regions: CompiledMapRegion[];
  };
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "compiledFacet".
 */
export interface CompiledFacet {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  title: string;
  note?: string;
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "compiledMapRegion".
 */
export interface CompiledMapRegion {
  /**
   * Locked domain identifier from domains.yaml (§5.9, F20).
   */
  domain: "mind" | "body" | "making" | "home" | "people" | "work-money" | "play" | "outdoors-nature";
  path: string;
  label?: {
    x: number;
    y: number;
  };
  bounds?: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  subregions?: {
    id: "expression" | "objects" | "systems";
    path: string;
  }[];
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "treeEntry".
 */
export interface TreeEntry {
  /**
   * Mutable slug; unique within the tree. Immutable after merge (§5.3).
   */
  id: string;
  contentVersion: number;
  title: string;
  summary: string;
  /**
   * Locked domain identifier from domains.yaml (§5.9, F20).
   */
  domain: "mind" | "body" | "making" | "home" | "people" | "work-money" | "play" | "outdoors-nature";
  secondaryDomains?: string[];
  subregion?: "expression" | "objects" | "systems";
  facets?: string[];
  archetype?: "single-track" | "dual-track" | "modular";
  milestoneCount: number;
  authors: string[];
  bundle: string;
}
